default_agent: GovEaseAgent
agents:
  GovEaseAgent:
    name: GovEaseAgent
    language: python
    node_version: '20'
    entrypoint: /Users/priyankabommideni/future-vision-agent/GovEase/app/GovEaseAgent/main.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/priyankabommideni/future-vision-agent/GovEase/app/GovEaseAgent
    aws:
      execution_role: arn:aws:iam::787156915839:role/AgentCore-govease-runtime
      execution_role_auto_create: false
      account: '787156915839'
      region: us-west-2
      ecr_repository: 787156915839.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-goveaseagent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: GovEaseAgent-rDhSp33iTV
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:787156915839:runtime/GovEaseAgent-rDhSp33iTV
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-goveaseagent-builder
      execution_role: arn:aws:iam::787156915839:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-72e52e2227
      source_bucket: bedrock-agentcore-codebuild-sources-787156915839-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
